### ISSUE TITLE
With two LoRas, if one of them is using the Block Weight format, the TE and BW from the first LoRA weight is applied globally

### ISSUE THREAD

**Issue by diodiogod** [nihedon/sd-webui-lora-block-weight#1]
Omg, sorry, here I am again...
After a bunch of testing, I think I understand now. The first LoRA is dictating the weight of the Text Encoder and the Blocks if they are set to the second lora (probably all loras?).
An easy way to check this without opening Forge and Auto1111 is simply inverting the order of the LoRAs in the prompt. You will get different results, and it shouldn't matter, as far as I know and tested.
 
 So a lora:1:lbw=0.5,1,1,1,1,1,1,1,1,1,1,1 will apply all that to the second lorax:lbw=xxx (doesn't matter the weight)
<img src="https://github.com/user-attachments/assets/fa70adbc-16c6-47da-856e-967964beef66" height="150">

**Comment by nihedon** [comment]
@diodiogod 
Ah, I also felt that something was behaving strangely when I was using it. There might be an error somewhere in the weight logic. Thank you for providing such detailed test results!

However, it’s possible that Forge might be caching some data to optimize image generation, which could be causing this issue. In that case, we may need to rebuild a new LBW that isn’t compatible with A1111.

**Comment by nihedon** [comment]
@diodiogod 
The issue was actually due to a bug I introduced when making adjustments for Forge, regardless of the Forge structure. I’ve fixed it, so please check again.

**Comment by diodiogod** [comment]
This is mostly working! Thanks. 
But there is still some kind of bug happening, I'm trying to pin it down.

Apparently when the first LoRA is not using BW and the second is, the first time Forges makes an image it will work normally, let's say:
```
1- <loraPerson:1><loraStyle:1:lbw=1,0.45,0.45,0.45,0.5,0.5,0.5,0.55,0.55,0.55,0.5,0.55>
```
Then, if I change the second Lora, (you need to keep using BW format), it will ignore whatever change you did. Even zeroing all blocks. 

For example:
```
2- <loraPerson:1><loraStyle:1:lbw=0,0,0,0,0,0,0,0,0,0,0,0> ## (this will behave as the previous generation, the style will be applied, and it shouldn't because it's all zeros).
```

EXCEPT if you change the normal Lora weight syntax, that comes right after the name. SO if I actually do this:
```
3- <loraPerson:1><loraStyle:0.9:lbw=0,0,0,0,0,0,0,0,0,0,0,0> ## (it will see the changes in the blocks and the "Style" LoRa won't have any effect because all blocks are zeroed out)
```

Changing the first lora weight also triggers the second LoRA reading of blocks, another example in three generations:
```
1- <loraPerson:1><loraStyle:0.9:lbw=1,1,1,1,1,1,1,1,1,1,1,1> ## normal behavior
2- <loraPerson:1><loraStyle:0.9:lbw=0,0,0,0,0,0,0,0,0,0,0,0> ## weird, bug, generates the same image as before
3- <loraPerson:0.9><loraStyle:0.9:lbw=0,0,0,0,0,0,0,0,0,0,0,0> ## normal behavior, triggers the reading of blocks
```

I don't think this bug happens if the LoRA with BW comes in first. You can change the Block Weights and they will be read correctly.

This bug explains why on my new XY plot image 10, 11 and 12 did not change at all comparing to image 9 (third line is the updated version):

<img src="https://github.com/user-attachments/assets/d292b6ec-05df-4af6-b130-0d2ac20bed9b" height="200">

**Comment by diodiogod** [comment]
I see you pushed another commit, maybe you caught that bug I described? I'll test the new version right now!

**Comment by diodiogod** [comment]
I tested the new version, the bug described here still happens https://github.com/nihedon/sd-webui-lora-block-weight/issues/1#issuecomment-2335200093

**Comment by nihedon** [comment]
@diodiogod 
Thank you once again for the detailed bug report.
Yes, I was aware of this issue and thought I had fixed it. However, after testing, I found that it wasn’t actually resolved as you reported, and there was a simple coding mistake... I’ve fixed it now, so please give it a try.

**Comment by diodiogod** [comment]
> @diodiogod Thank you once again for the detailed bug report. Yes, I was aware of this issue and thought I had fixed it. However, after testing, I found that it wasn’t actually resolved as you reported, and there was a simple coding mistake... I’ve fixed it now, so please give it a try.

You did it, it's all working just like it should! Thank you very much! You are awesome!

<img src="https://github.com/user-attachments/assets/336bc25f-1881-47ad-b8aa-c284c8e0ba1a" height="200">
